# Generated by Django 3.2.25 on 2026-04-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='checkout',
        ),
    ]
